ProgrammersBlog.Mvc/Areas/Admin/Controllers/ArticleController.cs
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ProgrammersBlog.Services.Abstract;
using ProgrammersBlog.Shared.Utilities.Results.ComplexTypes;
using ProgrammersBlog.Shared.Utilities.Results.Concrete;

namespace ProgrammersBlog.Mvc.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ArticleController : Controller
    {
        private readonly IArticleService _articleService;

        public ArticleController(IArticleService articleService)
        {
            _articleService=articleService;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            //var result = await _articleService.GetAllByNonDeleted();
            //if (result.ResultStatus == ResultStatus.Success)
            //{
            //    return View(result.Data);
            //}
            ////return View(result.Data);
            //return NotFound();
            var result = await _articleService.GetAllByNonDeleted();
            return View(result.Data);
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        public JsonResult GetAll(List<int> data=null)
        {


            //var articles = await _articleService.GetAllByNonDeleted();
            //var result = articles.Data.Articles.ToList();
            //return Json(new { rows = result, page = 1 }, new Newtonsoft.Json.JsonSerializerSettings());
            var articles = _articleService.GetAllByNonDeletedDeneme();
            return Json(new { rows = articles, page = 1 }, new Newtonsoft.Json.JsonSerializerSettings());


        }
        [HttpPost]
        public async Task<JsonResult> Delete(int articleId)
        {
            var result = await _articleService.Delete(articleId, "Ahmet Çiftçi");
            var deletedCategory = JsonSerializer.Serialize(result.Data);
            return Json(deletedCategory);
        }
        [HttpGet]
        public async Task<IActionResult> Get(int articleId)
        {
            var result = await _articleService.Get(articleId);
            if (result.ResultStatus==ResultStatus.Success)
            {
                return PartialView("_ArticleDetailsPartial",result.Data);
            }
            else
            {
                return NotFound();
            }
        }
    }
}

ProgrammersBlog.Mvc/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProgrammersBlog.Entities.Dtos;
using ProgrammersBlog.Mvc.Areas.Admin.Models;
using ProgrammersBlog.Services.Abstract;
using ProgrammersBlog.Shared.Utilities.Extensions;
using ProgrammersBlog.Shared.Utilities.Results.ComplexTypes;
using System.Text.Json;
using System.Threading.Tasks;

namespace ProgrammersBlog.Mvc.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin,Editor")]
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;
        //private ProgrammersBlogContext _context;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }
        public async Task<IActionResult> Index()
        {
            var result = await _categoryService.GetAllByNonDeleted();
            return View(result.Data);

        }
        [HttpGet]
        public IActionResult Add()//parçalı view döneceğimiz için asenkron olmasına gerek yok
        {
            return PartialView("_CategoryAddPartial");
        }
        [HttpPost]
        public async Task<IActionResult> Add(CategoryAddDto categoryAddDto)//parçalı view döneceğimiz için asenkron olmasına gerek yok
        {
            if (ModelState.IsValid)//model içinde bilgiler doğru olarak gelmiş mi
            {
                var result = await _categoryService.Add(categoryAddDto, "Ahmet Çiftçi");
                if (result.ResultStatus == ResultStatus.Success)
                {
                    var categoryAddAjaxModel = JsonSerializer.Serialize(new CategoryAddAjaxViewModel
                    {
                        CategoryDto = result.Data,
                        CategoryAddPartial = await this.RenderViewToStringAsync("_CategoryAddPartial", categoryAddDto)//string parse edip verme
                    });
                    return Json(categoryAddAjaxModel);//javascriptin anlayabilmesi için
                }
            }
            var categoryAddAjaxErorModel = JsonSerializer.Serialize(new CategoryAddAjaxViewModel
            {
                //partial içindeki inputlarla ilgili hata mesajları
                CategoryAddPartial = await this.RenderViewToStringAsync("_CategoryAddPartial", categoryAddDto)//string parse edip verme
            });
            return Json(categoryAddAjaxErorModel);
        }
        public async Task<JsonResult> GetAllCategories()
        {
            //using (ProgrammersBlogContext _context = new ProgrammersBlogContext())
            //{
            var categories = await _categoryService.GetAllByNonDeleted();
                //var result = _context.Categories.ToList<Category>();
            return Json(new { rows = categories.Data.Categories, page = 1 }, new Newtonsoft.Json.JsonSerializerSettings());
            //}
            //var result = await _categoryService.GetAllByNonDeleted();
            ////var categories = JsonSerializer.Serialize(result.Data.Categories);
            //var categories = JsonSerializer.Serialize(result.Data, new JsonSerializerOptions
            //{
            //    ReferenceHandler = ReferenceHandler.Preserve
            //});
            //return Json(new { page=1, rows=categories});

        }
        //[HttpGet]
        //public async Task<JsonResult> Delete(int Id)//create a [HttpPost] for delete method
        //{
        //    var result = await _categoryService.Get(Id);
        //    var deletedCategory = JsonSerializer.Serialize(result.Data,new JsonSerializerOptions
        //    {
        //        ReferenceHandler = ReferenceHandler.Preserve
        //    });
        //    return Json(deletedCategory);

        //}

        [HttpPost]
        public async Task<JsonResult> Delete(int categoryId)//başka bir parametre daha girmem gerekiyor overload işlemi olduğu için methodların aynı olmaması gerekiyor.
        {
            var result = await _categoryService.Delete(categoryId, "Ahmet Çiftçi");
            var deletedCategory = JsonSerializer.Serialize(result.Data);
            return Json(deletedCategory);
        }
        [HttpGet]
        public async Task<IActionResult> Update(int categoryId)//parçalı view döneceğimiz için asenkron olmasına gerek yok
        {
            var result = await _categoryService.GetCategoryUpdateDto(categoryId);
            if (result.ResultStatus==ResultStatus.Success)
            {
                return PartialView("_CategoryUpdatePartial", result.Data);
            }
            else
            {
                return NotFound();
            }
        }
        [HttpPost]
        public async Task<IActionResult> Update(CategoryUpdateDto categoryUpdateDto)//parçalı view döneceğimiz için asenkron olmasına gerek yok
        {
            if (ModelState.IsValid)//model içinde bilgiler doğru olarak gelmiş mi
            {
                var result = await _categoryService.Update(categoryUpdateDto, "Ahmet Çiftçi");
                if (result.ResultStatus == ResultStatus.Success)
                {
                    var categoryUpdateAjaxModel = JsonSerializer.Serialize(new CategoryUpdateAjaxViewModel
                    {
                        CategoryDto = result.Data,
                        CategoryUpdatePartial = await this.RenderViewToStringAsync("_CategoryUpdatePartial", categoryUpdateDto)//string parse edip verme
                    });
                    return Json(categoryUpdateAjaxModel);//javascriptin anlayabilmesi için
                }
            }
            var categoryUpdateAjaxErrorModel = JsonSerializer.Serialize(new CategoryUpdateAjaxViewModel
            {
                CategoryUpdatePartial = await this.RenderViewToStringAsync("_CategoryUpdatePartial", categoryUpdateDto)//string parse edip verme
            });
            return Json(categoryUpdateAjaxErrorModel);
        }
    }
}

ProgrammersBlog.Mvc/Areas/Admin/Views/Article/Add.cshtml
@{
    Layout = "_Layout";
    ViewBag.Title = "Makale Ekle";
}
<ol class="breadcrumb mb-3 mt-2">
    <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Home" asp-action="Index">Admin</a></li>
    <li class="breadcrumb-item active"><a asp-area="Admin" asp-controller="Article" asp-action="Index">Makaleler</a></li>
    <li class="breadcrumb-item active"><a asp-area="Admin" asp-controller="Article" asp-action="Index">Ekle</a></li>
</ol>
<form asp-controller="Article" asp-action="Add" method="post" enctype="multipart/form-data">
    <div class="row mt-2">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <input type="text" id="articleTitle" class="form-control" placeholder="Makale Başlığı" />
                    </div>
                    <div class="form-group">
                        <textarea id="text-editor"></textarea>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    Temel Konfigürasyonlar
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label for="categoryList">Kategori</label>
                        <select id="categoryList" class="form-control">
                            <option disabled="disabled">Lütfen bir kategori seçiniz...</option>
                            <option>C#</option>
                            <option>C++</option>
                            <option>Javascript</option>
                            <option>Python</option>
                            <option>Java</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="datepicker">Tarih</label>
                        <input type="text" id="datepicker" class="form-control" value="@DateTime.Now.ToShortDateString()" />
                    </div>
                    <div class="form-group">
                        <label for="thumbnailUpload">Küçük Resim</label>
                        <input type="file" id="thumbnailUpload" accept="image/*" class="form-control-file" />
                    </div>
                    <div class="form-check">
                        <input type="checkbox" id="isActive" class="form-check-input" />
                        <label for="isActive" class="form-check-label">Aktif Mi?</label>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block mt-4">Kaydet</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-12 mt-2">
            <div class="card">
                <div class="card-header">
                    SEO Optimizasyonu
                </div>
                <div class="card-body">
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="seoWriter">Yazar Adı</label>
                            <input type="text" id="seoWriter" class="form-control" />
                        </div>
                        <div class="form-group col-md-6">
                            <label for="seoTags">Etiketler</label>
                            <input type="text" id="seoTags" class="form-control" />
                        </div>
                        <div class="form-group col-md-12">
                            <label for="seoDescription">Makale Açıklaması</label>
                            <textarea id="seoDescription" class="form-control"></textarea>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
@section Scripts
    {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Trumbowyg/2.23.0/trumbowyg.min.js" integrity="sha512-sffB9/tXFFTwradcJHhojkhmrCj0hWeaz8M05Aaap5/vlYBfLx5Y7woKi6y0NrqVNgben6OIANTGGlojPTQGEw==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Trumbowyg/2.23.0/langs/tr.min.js" integrity="sha512-+HGzdrYvtA0U9cp5kJad8OpjTvUi6ywZ9z9kXFGiV3EaAR1II5X6lfulUm6/F9GKesHW+jHFfAqwXK0juybvMw==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Trumbowyg/2.23.0/plugins/colors/trumbowyg.colors.min.js" integrity="sha512-iT7g30i1//3OBZsfoc5XmlULnKQKyxir582Z9fIFWI6+ohfrTdns118QYhCTt0d09aRGcE7IRvCFjw2wngaqRQ==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Trumbowyg/2.23.0/plugins/emoji/trumbowyg.emoji.min.js" integrity="sha512-C1y8Ma4rukPZAgoB+9AWiKNMWXvWXGDygpcYuL/lM3YKUcZLUgFwF8brKYML73a5YeZ4y7hmY3604Tzx4f4k0Q==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Trumbowyg/2.23.0/plugins/fontfamily/trumbowyg.fontfamily.min.js" integrity="sha512-tDDpWlhruXFSzPin7PeSOo/ZklJv354ZUibgoTnthgO9lQUiNn4etCFGNwT4c3WUCZ1jWZgOVrXGMqiApe9sBg==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Trumbowyg/2.23.0/plugins/fontsize/trumbowyg.fontsize.min.js" integrity="sha512-DOJaq3OCe5hLSr73aQBMiJY4kc+L5UwessOl6g2oxyy7VDnZVWt+TgWVy2nh2ypf7bwoaxZmPnIMiRC5PNZecA==" crossorigin="anonymous"></script>
    <script src="~/js/articleAdd.js" type="application/ecmascript"></script>
}
@section Styles
    {
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Trumbowyg/2.23.0/ui/trumbowyg.min.css" integrity="sha512-iw/TO6rC/bRmSOiXlanoUCVdNrnJBCOufp2s3vhTPyP1Z0CtTSBNbEd5wIo8VJanpONGJSyPOZ5ZRjZ/ojmc7g==" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Trumbowyg/2.23.0/plugins/colors/ui/trumbowyg.colors.min.css" integrity="sha512-8dXb2ITE13jLrqqGDVTU8kKl9vHZI9E4TpZGyfhevHeF+/cWWA17wVj+SKX3+QHqZISiGihaCOyK3nA152ShDg==" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Trumbowyg/2.23.0/plugins/emoji/ui/trumbowyg.emoji.min.css" integrity="sha512-T2q2UM7Pm3t6Fu0VTRcuVMuaQf3/wP1aFi+/NyvpoVV0VBxN1Pqlmq57Jfg1IPRQCfFQOPLKBwoXA28+1gd/Ow==" crossorigin="anonymous" />
}

ProgrammersBlog.Mvc/Areas/Admin/Views/Article/Index.cshtml
@model ProgrammersBlog.Entities.Dtos.ArticleListDto
@{
    Layout = "_Layout";
    ViewBag.Title = "Makaleler";
}
<ol class="breadcrumb mb-3 mt-2">
    <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Home" asp-action="Index">Admin</a></li>
    <li class="breadcrumb-item active"><a asp-area="Admin" asp-controller="Article" asp-action="Index">Makaleler</a></li>
</ol>
<div id="modalPlaceHolder" aria-hidden="true"></div>

<form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
    <div class="input-group">
        <input class="form-control" type="text" placeholder="Kategori Ara" aria-label="Search" aria-describedby="basic-addon2" />
    </div>
</form>
<br />
<table id="list"></table>
<div id="pager"></div>

<button id="btnAdd" type="button" class="btn btn-info btn-sm"><span class="far fa-plus-square"></span> Ekle</button>
@*<input type="button" name="button" id="btnAdd" value="Ekle">*@
@section Scripts
    {
    <script type="text/javascript">
        function editLink(cellValue, options, rowdata, action) {
            var a = "";
            //bi alt satırda href içerisinde link tanımladık ve row.id'yi çağırmış olduk.<a ile bir link açtık ve içine span verdik.
            a += "<a href='/Admin/Category/Delete/" + rowdata.Id + "' title='" + " ><span class='nav-link-icon'><span class='fas fa-trash-alt text-danger'></span></span></a>";
            a += '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;';
            return a;
        }

        $(document).ready(function () {
            var modal = document.getElementById('modalPlaceHolder');
            var btn = document.getElementById('btnAdd');
            //$(function () {
            //    const url = '/Admin/Category/Add/';//const değiştirilemez veri tipidir var değiştirilebilir veri tipidir.
            //    const placeHolderDiv = $('#modalPlaceHolder');
            //    $('#btnAdd').click(function () {
            //        $.get(url).done(function (data) {
            //            placeHolderDiv.html(data);
            //            placeHolderDiv.find(".modal").modal('show');
            //        });
            //    });
            var detailsFormatter = function (cellVal, options, rowObject) {
                return "<button class=\"btn btn-dark btn-sm btn-details\"><span class=\"glyphicon glyphicon-edit\"></span></button>";
            };
            var deleteFormatter = function (cellVal, options, rowObject) {
                return "<button class=\"btn btn-dark btn-sm btn-delete\"><span class=\"far fa-trash-alt\"></span></button>";
            };

            function deleteLink(cellValue, options, rowdata, action) {
                var a = "";
                a += "<a href='/Company/Activity/Delete/" + rowdata.Id + "' title='" + "onclick='DeleteConfirm(this,event);return false;' ><span class='nav-link-icon'><span class='fas fa-trash-alt text-danger'></span></span></a>";
                a += '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;';
                return a;
            }

            $("#list").jqGrid({
                url: '/Admin/Article/GetAll/',
                datatype: "json",
                mtype: "GET", //GET POST FARKINA BAK
                colNames: ["Id", "Title", "CategoryName", "Content", "Details", "Delete"],
                colModel: [
                    {
                        label: 'Id',
                        name: 'Id',
                        key: true,
                        width: 75
                    }, {
                        label: 'Title',
                        name: 'Title',
                        width: 150
                    }, {
                        label: 'CategoryName',
                        name: 'CategoryName',
                        width: 150
                    }, {
                        label: 'Content',
                        name: 'Content',
                        width: 150
                    },
                    {
                        label: 'Details',
                        name: 'Details',
                        key: true,
                        width: 20,
                        formatter: detailsFormatter
                    },
                    {
                        label: 'Delete',
                        name: 'Delete',
                        key: true,
                        width: 20,
                        formatter: deleteFormatter //add, delete ve edit için fonksiyonlar oluşturacağım,bu fonksiyonları formatter olarak vereceğim
                    }
                ],

                //formatter:function(event e, ) add
                viewrecords: true,
                height: 250,
                pager: "#pager",
                autowidth: true,
                multiselect: false
                //pager-you have to choose here what icons should appear at the bottom
                //like edit,create,delete icons
            });


            //$(function () {
            //    const url = '@Url.Action("Add", "Category")';
            //    const placeHolderDiv = $('#modalPlaceHolder');
            //    $('#btnAdd').click(function () {
            //        $.get(url).done(function (data) {
            //            placeHolderDiv.html(data);
            //            placeHolderDiv.find(".modal").modal("show");
            //        });
            //    });
            //    placeHolderDiv.on('click',
            //        '#btnSave',
            //        function (event) {
            //            event.preventDefault();
            //            const form = $('#form-category-add');
            //            const actionUrl = form.attr('action');
            //            const dataToSend = form.serialize();
            //            $.post(actionUrl, dataToSend).done(function (data) {
            //                console.log(data);
            //                const categoryAddAjaxModel = jQuery.parseJSON(data);
            //                console.log(categoryAddAjaxModel);
            //                const newFormBody = $('.modal-body', categoryAddAjaxModel.CategoryAddPartial);
            //                placeHolderDiv.find('.modal-body').replaceWith(newFormBody);
            //                placeHolderDiv.find('.modal').modal('hide');
            //                //jQuery("#list").trigger("reloadGrid");
            //                toastr.success(`${categoryAddAjaxModel.CategoryDto.Message}`, 'Başarılı İşlem!');
            //                $('#list').trigger('reloadGrid');
            //            });
            //        });
            //});

            $(document).on('click',
                '.btn-delete',
                function (event) {
                    event.preventDefault();
                    var id = $('#list').jqGrid('getGridParam', 'selrow');
                    var cellValue = $('#list').jqGrid('getCell', id, 'Id');
                    console.log(cellValue);
                    //const id = $(this).attr('Id'); //calismiyor
                    Swal.fire({
                        title: 'Silmek istediğinize emin misiniz?',
                        text: 'Makale silinecektir.',
                        icon: 'warning',
                        showCancelButton: true,
                        confirmButtonColor: '#3085d6',
                        cancelButtonColor: '#d33',
                        confirmButtonText: 'Evet, silmek istiyorum.',
                        cancelButtonText: 'Hayır, silmek istemiyorum.'
                    }).then((result) => {
                        if (result.isConfirmed) {
                            $.ajax({
                                type: 'POST',
                                datatype: 'json',
                                data: { articleId: cellValue },
                                url: '/Admin/Article/Delete/',
                                success: function (data) {
                                    const articleDto = jQuery.parseJSON(data);
                                    console.log(data);
                                    if (articleDto.ResultStatus === 0) {
                                        
                                        Swal.fire(
                                            'Silindi!',
                                            'makale başarıyla silinmiştir.',
                                            'success');
                                        $('#list').trigger('reloadGrid');
                                    }
                                }
                            });
                            console.log(id);

                        }
                    });
                });
            $(function () {
                const url = '/Admin/Article/Get/';
                const placeHolderDiv = $('#modalPlaceHolder');
                $(document).on('click',
                    '.btn-details',
                    function (event) {
                        event.preventDefault();
                        var id = $('#list').jqGrid('getGridParam', 'selrow');
                        var cellValue = $('#list').jqGrid('getCell', id, 'Id');
                        console.log(cellValue);
                        $.get(url, { articleId: cellValue }).done(function (data) {
                            placeHolderDiv.html(data);
                            placeHolderDiv.find('.modal').modal('show');
                        }).fail(function () {
                            toastr.error("Bir Hata Oluştu.");
                        });
                    });});
            //    placeHolderDiv.on('click',
            //        '#btnUpdate',
            //        function (event) {
            //            const form = $('#form-category-update');
            //            const actionUrl = form.attr('action');
            //            const dataToSend = form.serialize();
            //            $.post(actionUrl, dataToSend).done(function (data) {
            //                const categoryUpdateAjaxModel = jQuery.parseJSON(data);
            //                console.log(categoryUpdateAjaxModel);
            //                const newFormBody = $('.modal-body', categoryUpdateAjaxModel.CategoryUpdatePartial);
            //                placeHolderDiv.find('.modal-body').replaceWith(newFormBody);
            //                const isValid = newFormBody.find('[name=IsValid]').val() === 'True';
            //                if (isValid) {
            //                    placeHolderDiv.find('.modal').modal('hide');
            //                    $('#list').trigger('reloadGrid');
            //                    toastr.success(`${categoryUpdateAjaxModel.CategoryDto.Message}`, "Başarılı İşlem");
            //                }
            //            });
            //        });
            //});
            //$(function() {
            //
            //    const placeHolderDiv = $('#modalPlaceHolder');

            //    $(document).on('click',
            //        '.btn-update',
            //        function(event) {
            //            event.preventDefault();
            //            //id alamıyom :(
            //            $.get(url).done(function() {
            //                placeHolderDiv.html(data);
            //                placeHolderDiv.find('.modal').modal('show');
            //            });
            //        });
            //});
        });

                //    /* Ajax GET / _CategoryAddPartial'ı Modal Form olarak almak burada bitiyor. */

                //    /* Ajax POST / FormData'yı CategoryAddDto olarak yayınlamak burada başlıyor. */

                //    placeHolderDiv.on('click',
                //        '#btnSave',
                //        function (event) {
                //            event.preventDefault();
                //            const form = $('#form-category-add');
                //            const actionUrl = form.attr('action');
                //            const dataToSend = form.serialize();
                //            $.post(actionUrl, dataToSend).done(function (data) {
                //                console.log(data);
                //                const categoryAddAjaxModel = jQuery.parseJSON(data);
                //                console.log(categoryAddAjaxModel);
                //                const newFormBody = $('.modal-body', categoryAddAjaxModel.CategoryAddPartial);
                //                placeHolderDiv.find('.modal-body').replaceWith(newFormBody);
                //                const isValid = newFormBody.find('[name="IsValid"]').val() === 'True';
                //                if (isValid) {
                //                    placeHolderDiv.find('.modal').modal('hide');
                //Ekleme Silme Güncelleme butonlarının içini doldur - Arama işlemini yap
                //Ajax işlemlerine iyice bak araştır. javascript ile iş kuralları da yazman gerekiyor.
    </script>
    }

ProgrammersBlog.Mvc/Areas/Admin/Views/Article/_ArticleDetailsPartial.cshtml
@model ProgrammersBlog.Entities.Dtos.ArticleDetailsDto
<div class="modal fade" tabindex="-1"role="dialog"aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><span class="fas fa-eye"></span> Makale Detayı</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="İptal">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form asp-action="Get" id="form-article-details">
            @*<input name="IsValid"type="hidden"value="@ViewData.ModelState.IsValid.ToString()" />*@
            <div asp-validation-summary="All" class="text-danger" id ="validation-summary" aria-hidden="true"style="display:none"></div>
            <div class="form-group">
                <label asp-for="Title"></label>
                        <input class="form-control" asp-for="Title" />
                        <span class="text-danger" asp-validation-for="Title"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryName"></label>
                        <input class="form-control" asp-for="CategoryName" />
                        <span class="text-danger" asp-validation-for="CategoryName"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content"></label>
                        <input class="form-control" asp-for="Content" />
                        <span class="text-danger" asp-validation-for="Content"></span>
            </div>
        </form>
      </div>
    </div>
  </div>
</div>